import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import { Button, ButtonGroup } from "@chakra-ui/react";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Admin App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>Sales</h1>
          <button style={{ color: "white", border: "1px solid white" }}>
            LOGIN
          </button>
          <Button
            onClick={() => {
              router.push("/login");
            }}
            colorScheme="green"
          >
            LOGIN
          </Button>
        </div>
      </main>
    </>
  );
};

export default Home;
